#!/bin/sh /etc/rc.common

START=98
STOP=10

USE_PROCD=1

CONFIG_FILE="/etc/config/idclass"

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/idclass -c "$CONFIG_FILE"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	# 直接 killall 即可，procd 会处理
	killall idclass 2>/dev/null
}

reload_service() {
	stop
	start
}